In [14]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

docs = [
    'go india',
    'india india',
    'hip hip hurray',
    'jeetega bhai jeetega india jeetega',
    'bharat mata ki jai',
    'kohli kohli',
    'sachin sachin',
    'dhoni dhoni',
    'modi ji ki jai',
    'inquilab zindabad'
]

In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()


c:\Users\gadhv\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\gadhv\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\gadhv\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framewo

In [6]:
tokenizer.fit_on_texts(docs)

In [7]:
len(tokenizer.word_index)

17

In [8]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [9]:
from keras.utils import pad_sequences 
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [19]:
model = Sequential()
model.add(Embedding(18,output_dim=2,input_length=5))

model.summary()

c:\Users\gadhv\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.compile('adam','accuracy')

In [21]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step
[[[ 0.00903734  0.04386291]
  [-0.00929634 -0.00987095]
  [ 0.00729705  0.03690192]
  [ 0.00729705  0.03690192]
  [ 0.00729705  0.03690192]]

 [[-0.00929634 -0.00987095]
  [-0.00929634 -0.00987095]
  [ 0.00729705  0.03690192]
  [ 0.00729705  0.03690192]
  [ 0.00729705  0.03690192]]

 [[-0.01221048 -0.00257065]
  [-0.01221048 -0.00257065]
  [ 0.04754769 -0.02043977]
  [ 0.00729705  0.03690192]
  [ 0.00729705  0.03690192]]

 [[-0.0099104   0.02838478]
  [ 0.01151853  0.03760945]
  [-0.0099104   0.02838478]
  [-0.00929634 -0.00987095]
  [-0.0099104   0.02838478]]

 [[-0.04999421 -0.03757098]
  [ 0.00323396  0.04078256]
  [ 0.01687712 -0.0044516 ]
  [ 0.04867962 -0.00794937]
  [ 0.00729705  0.03690192]]

 [[ 0.02403561 -0.02990276]
  [ 0.02403561 -0.02990276]
  [ 0.00729705  0.03690192]
  [ 0.00729705  0.03690192]
  [ 0.00729705  0.03690192]]

 [[-0.00901591  0.02104808]
  [-0.00901591  0.02104808]
  [ 0.00729705  0.03690192]
  [ 0.00729705  0.0369019

In [22]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras import Sequential
from keras.layers import Embedding, Flatten, Dense , SimpleRNN


In [23]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [24]:
X_train = pad_sequences(X_train, padding='post', maxlen=50)
X_test = pad_sequences(X_test,padding='post', maxlen=50)

In [25]:
X_train.shape

(25000, 50)

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.build((None, 50)) 
model.summary()


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)